/**
 * Inline the above-the-fold CSS and de-block the rest.
 *
 * node tools/build-css.mjs [--check]
 *
 * Rationale: Lighthouse reported 250ms of render-blocking time from six
 * stylesheets. tokens/base/hero are what the first viewport needs, so they go
 * inline in <head> — one round trip instead of three. sections/episodes/blocks
 * only style below-the-fold content, so they load async via media="print" +
 * onload, with a <noscript> fallback.
 *
 * Run this AFTER any track edits a stylesheet, or index.html and css/ will
 * drift. --check exits non-zero if they have.
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const INLINE = ["tokens", "base", "hero"];
const DEFER = ["sections", "episodes", "blocks"];

const strip = (css) => css.replace(/\/\*[\s\S]*?\*\//g, "").trim();
const critical = INLINE.map((n) => strip(fs.readFileSync(path.join(ROOT, `css/${n}.css`), "utf8"))).join("\n");

const MARK_A = "<!-- Inlined critical CSS:";
const MARK_B = "</style>\n";

function build() {
  let html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");

  // Replace the previous inline block, if any.
  const a = html.indexOf(MARK_A);
  if (a !== -1) {
    const b = html.indexOf(MARK_B, a);
    html = html.slice(0, a) + html.slice(b + MARK_B.length);
  }

  // Move every stylesheet link to the deferred form (idempotent).
  for (const n of INLINE) {
    html = html.replace(
      new RegExp(`<link rel="stylesheet" href="css/${n}\\.css"[^>]*>\\n?`, "g"),
      ""
    );
  }
  for (const n of DEFER) {
    const deferred = `<link rel="stylesheet" href="css/${n}.css" media="print" onload="this.media='all'" />\n<noscript><link rel="stylesheet" href="css/${n}.css" /></noscript>`;
    const re = new RegExp(`(?:<link rel="stylesheet" href="css/${n}\\.css"[^>]*>\\n?)(?:<noscript><link rel="stylesheet" href="css/${n}\\.css" /></noscript>\\n?)?`, "g");
    html = html.replace(re, deferred + "\n");
  }

  const inline = `${MARK_A} tokens + base + hero are the above-the-fold styles; inlining\n     them removes the largest render-blocking round trip. Below-the-fold sheets load\n     async via media=print/onload. GENERATED by tools/build-css.mjs — do not edit\n     by hand; edit css/*.css and re-run.\n     -->\n<style>\n${critical}\n</style>\n`;
  html = html.replace('<script type="module" src="js/main.js"></script>', inline + '<script type="module" src="js/main.js"></script>');

  fs.writeFileSync(path.join(ROOT, "index.html"), html);
  return critical.length;
}

const current = build();
const expected = (() => {
  const html = fs.readFileSync(path.join(ROOT, "index.html"), "utf8");
  const a = html.indexOf("<style>");
  const b = html.indexOf("</style>");
  return html.slice(a + 7, b);
})();

if (process.argv.includes("--check")) {
  if (expected.trim() !== critical.trim()) {
    console.error("FAIL index.html critical CSS is stale — run: node tools/build-css.mjs");
    process.exit(1);
  }
  console.log("ok index.html critical CSS matches css/*.css");
} else {
  console.log(`inlined ${current} bytes of critical CSS from ${INLINE.join(", ")}`);
  console.log(`deferred: ${DEFER.join(", ")}`);
}